// Pre-baked Sentinel-2 sample pairs for the flood demo + alert simulator.
//
// Each entry is a complete scenario: 4 PNGs (pre+current × RGB+SWIR), the
// location's coordinates (so alerts can pin to a map), and the human
// labels for the source/UI. Two of the four are reliably alert-eligible
// per the ground-truth annotations in finetune-flood/data/raw/ — Mocoa 2017
// and San Benito Abad 2021. The other two test borderline conditions
// (cloud-affected baseline, chronic-wetland confounding).

export interface FloodSample {
  id: string;
  /** Slug for grouping by municipality. Stable across redeploys. */
  location_slug: string;
  location_label: string;
  region: "la-mojana" | "putumayo";
  /** Centre of the 5 km Sentinel-2 tile, WGS-84. */
  lon: number;
  lat: number;
  event_date: string;
  event_label: string;
  description: string;
  expected_summary: string;
  /** Whether ground-truth labels indicate the threshold rule should fire.
   *  flood_present && populated_area_affected && !image_quality_limited. */
  expected_alert: boolean;
  paths: {
    pre_rgb: string;
    pre_swir: string;
    cur_rgb: string;
    cur_swir: string;
  };
  /** Pre-baked watermarked thumbnail (~280×280, "ONBOARD · LFM2-VL"
   *  badge bottom-strip). Shipped with each alert so the Tauri app can
   *  render it offline. Generated by ImageMagick from the cur_rgb tile. */
  thumbnail: string;
}

export const FLOOD_SAMPLES: FloodSample[] = [
  {
    id: "san-benito-abad-2021",
    location_slug: "san_benito_abad",
    location_label: "San Benito Abad, Sucre",
    region: "la-mojana",
    lon: -75.0319,
    lat: 8.9275,
    event_date: "2021-09-15",
    event_label: "Cara de Gato breach · Sept 2021",
    description: "First wave of the 2021–2023 triple-dip La Niña. The 27 Aug 2021 dike failure inundated 11 municipalities; San Benito Abad is one of the worst-hit. Clear visibility in both pre and current views.",
    expected_summary: "severe flood · populated area · infrastructure at risk · alert publishes",
    expected_alert: true,
    paths: {
      pre_rgb:  "/assets/samples/san-benito-abad-2021-pre-rgb.png",
      pre_swir: "/assets/samples/san-benito-abad-2021-pre-swir.png",
      cur_rgb:  "/assets/samples/san-benito-abad-2021-cur-rgb.png",
      cur_swir: "/assets/samples/san-benito-abad-2021-cur-swir.png",
    },
    thumbnail: "/assets/samples/san-benito-abad-2021-thumb.png",
  },
  {
    id: "mocoa-2017",
    location_slug: "mocoa",
    location_label: "Mocoa, Putumayo",
    region: "putumayo",
    lon: -76.6534,
    lat: 1.1463,
    event_date: "2017-04-01",
    event_label: "Mocoa avalancha torrencial · Apr 2017",
    description: "Andean-foothill flash flood. The 31 Mar – 1 Apr 2017 event killed 335 people in minutes. The current tile shows post-event scarring across a populated area.",
    expected_summary: "severe flood · populated area affected · alert publishes",
    expected_alert: true,
    paths: {
      pre_rgb:  "/assets/samples/mocoa-2017-pre-rgb.png",
      pre_swir: "/assets/samples/mocoa-2017-pre-swir.png",
      cur_rgb:  "/assets/samples/mocoa-2017-cur-rgb.png",
      cur_swir: "/assets/samples/mocoa-2017-cur-swir.png",
    },
    thumbnail: "/assets/samples/mocoa-2017-thumb.png",
  },
  {
    id: "cara-de-gato-2024",
    location_slug: "san_jacinto_del_cauca",
    location_label: "San Jacinto del Cauca, Bolívar",
    region: "la-mojana",
    lon: -74.7167,
    lat: 8.25,
    event_date: "2024-05-06",
    event_label: "Cara de Gato dike breach · May 2024",
    description: "The 2024 re-breach at the same dike. Heavy cloud cover in the current tile makes this a stress test — the model should flag image_quality_limited if it can't see clearly.",
    expected_summary: "severe flood likely · cloud-bound, may suppress alert",
    expected_alert: false,
    paths: {
      pre_rgb:  "/assets/samples/cara-de-gato-2024-pre-rgb.png",
      pre_swir: "/assets/samples/cara-de-gato-2024-pre-swir.png",
      cur_rgb:  "/assets/samples/cara-de-gato-2024-cur-rgb.png",
      cur_swir: "/assets/samples/cara-de-gato-2024-cur-swir.png",
    },
    thumbnail: "/assets/samples/cara-de-gato-2024-thumb.png",
  },
  {
    id: "ayapel-peak-2022",
    location_slug: "ayapel",
    location_label: "Ayapel, Córdoba",
    region: "la-mojana",
    lon: -75.1389,
    lat: 8.3128,
    event_date: "2022-12-15",
    event_label: "La Mojana peak inundation · Dec 2022",
    description: "Wetland-margin tile at peak inundation, third year of the triple-dip La Niña. Tests the model's ability to distinguish chronic ciénaga from new flooding.",
    expected_summary: "moderate flood, wetland baseline preserved",
    expected_alert: false,
    paths: {
      pre_rgb:  "/assets/samples/ayapel-peak-2022-pre-rgb.png",
      pre_swir: "/assets/samples/ayapel-peak-2022-pre-swir.png",
      cur_rgb:  "/assets/samples/ayapel-peak-2022-cur-rgb.png",
      cur_swir: "/assets/samples/ayapel-peak-2022-cur-swir.png",
    },
    thumbnail: "/assets/samples/ayapel-peak-2022-thumb.png",
  },
];

export const SAMPLES_BY_ID = Object.fromEntries(FLOOD_SAMPLES.map((s) => [s.id, s]));
